name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
      - cron: "0 13 * * 1"  # Every Monday at 9AM EST

jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Setup environment
        run: |
            python -m pip install --upgrade pip
            pip install ".[tests,dev,examples]"

      - name: Run experiment
        run: |
          python scripts/eval.py ceviche_mode_converter reference_devices/ceviche/mode_converter/
          python scripts/eval.py metagrating reference_devices/metagrating/device1.csv
          python scripts/eval.py diffractive_splitter reference_devices/diffractive_splitter/device1.csv
          python scripts/eval.py photon_extractor reference_devices/photon_extractor/device1.csv
          python scripts/eval.py polarization_sorter reference_devices/polarization_sorter/device1.json
