name: CI

on:
  pull_request:
  push:
    branches:
      - main
  schedule:
      - cron: "0 13 * * 1"  # Every Monday at 9AM EST

jobs:
  experiment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: pyproject.toml

      - name: Setup environment
        run: |
            python -m pip install --upgrade pip
            pip install ".[tests,dev]"

      - name: Run experiment
        run: |
          mkdir experiment
          mkdir experiment/wid_0000
          mkdir experiment/wid_0001
          mkdir experiment/wid_0002
          python scripts/experiment.py --workers=1 --path="experiments/"
